# 02 - Baseline Classifier (TF-IDF + Logistic Regression)

Trains and evaluates the baseline category classifier used by default in the running pipeline.

In [1]:
import sys, pathlib
sys.path.insert(0, str(pathlib.Path.cwd().parent))
import pandas as pd
from src.config import settings
from src.classification.baseline import BaselineClassifier

df = pd.read_csv(settings.path('paths.complaints_csv'))
df['complaint_text'] = df['complaint_text'].fillna('')
df.shape

(10000, 18)

In [2]:
clf = BaselineClassifier(target_name='category')
metrics = clf.fit(df['complaint_text'].tolist(), df['category'].tolist())
print('accuracy:', metrics['accuracy'])
print('macro F1:', metrics['macro_f1'])
print('weighted F1:', metrics['weighted_f1'])

2026-08-31 04:04:06,582 | INFO     | src.classification.baseline | [category] baseline trained. acc=1.000 macro_f1=1.000

accuracy: 1.0
macro F1: 1.0
weighted F1: 1.0

In [3]:
import pandas as pd
pd.DataFrame(metrics['classification_report']).T

                  precision  recall  f1-score  support
Account                 1.0     1.0       1.0    141.0
Customer Service        1.0     1.0       1.0    116.0
Delivery                1.0     1.0       1.0    230.0
Fraud                   1.0     1.0       1.0     47.0
Other                   1.0     1.0       1.0     46.0
Payment                 1.0     1.0       1.0    296.0
Product Quality         1.0     1.0       1.0    129.0
Refund                  1.0     1.0       1.0    185.0
Subscription            1.0     1.0       1.0     92.0
Technical Issue         1.0     1.0       1.0    218.0
accuracy                1.0     1.0       1.0      1.0
macro avg               1.0     1.0       1.0   1500.0
weighted avg            1.0     1.0       1.0   1500.0

In [4]:
# Confusion matrix
import numpy as np
cm = pd.DataFrame(metrics['confusion_matrix'], index=metrics['labels'], columns=metrics['labels'])
cm

,Account,Customer Service,Delivery,Fraud,Other,Payment,Product Quality,Refund,Subscription,Technical Issue
Account,141,0,0,0,0,0,0,0,0,0
Customer Service,0,116,0,0,0,0,0,0,0,0
Delivery,0,0,230,0,0,0,0,0,0,0
Fraud,0,0,0,47,0,0,0,0,0,0
Other,0,0,0,0,46,0,0,0,0,0
Payment,0,0,0,0,0,296,0,0,0,0
Product Quality,0,0,0,0,0,0,129,0,0,0
Refund,0,0,0,0,0,0,0,185,0,0
Subscription,0,0,0,0,0,0,0,0,92,0
Technical Issue,0,0,0,0,0,0,0,0,0,218

**Note:** accuracy is very high (~100%) because the synthetic generator uses templated phrasing per subcategory — this reflects dataset separability, not a real-world performance claim. See README section 9/17/21 for discussion.